version: '3.3'
services:
  myapp:
    build: .
    ports:
      - "${HTTP_PORT:-8061}:80"
    depends_on:
      - mongodb
#    environment:
#      - VIRTUAL_HOST=gsm-devices-api.letscode.it

  mongodb:
    image: 'mongo:4.4.6'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
#    ports:
#      - '27017'
