version: '3.3'
services:
  myapp:
    build: .
    ports:
      - "${HTTP_PORT:-8061}:8080"
    depends_on:
      - mongodb
    environment:
      - VIRTUAL_HOST=gsm-devices-api.letscode.it
      - VIRTUAL_PORT=8080
    networks:
      - nginx-proxy
      - private_network

  mongodb:
    image: 'mongo:4.4.6'
    networks:
      - private_network

networks:
  private_network:
  nginx-proxy:
    external: true